# SecureEndpoint agent installer for Windows.
#
# Usage (generated by the console):
#   irm https://SERVER/downloads/install.ps1 | iex; Install-SemAgent -Server https://SERVER -Token sem_enr_xxx
# or, from a downloaded copy (elevated PowerShell):
#   .\install.ps1 -Server https://SERVER -Token sem_enr_xxx [-InsecureSkipVerify] [-CaFile C:\ca.pem]
#
# The script downloads sem-agent-windows-<arch>.exe from $Server/downloads/,
# verifies its SHA-256 against checksums.txt, installs it to
# C:\Program Files\SecureEndpoint\, enrolls the device and starts the
# "SecureEndpointAgent" Windows service.

function Install-SemAgent {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$Server,
        [Parameter(Mandatory = $true)][string]$Token,
        [switch]$InsecureSkipVerify,
        [string]$CaFile,
        [ValidateSet('', 'amd64', 'arm64')][string]$Arch = '',
        [string]$InstallDir = (Join-Path $env:ProgramFiles 'SecureEndpoint')
    )
    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'

    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'Install-SemAgent must run in an elevated (Run as Administrator) PowerShell.'
    }
    if ($Token -notmatch '^sem_enr_') { throw 'Token must be an enrollment token (sem_enr_...).' }

    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    if ($InsecureSkipVerify) {
        Write-Warning 'TLS certificate verification disabled (-InsecureSkipVerify). Use only for testing.'
        if ($PSVersionTable.PSVersion.Major -lt 6) {
            if (-not ('SemTrustAll' -as [type])) {
                Add-Type -TypeDefinition @'
using System.Net; using System.Net.Security; using System.Security.Cryptography.X509Certificates;
public static class SemTrustAll { public static bool Accept(object s, X509Certificate c, X509Chain ch, SslPolicyErrors e) { return true; } }
'@
            }
            [Net.ServicePointManager]::ServerCertificateValidationCallback = [Net.Security.RemoteCertificateValidationCallback] [SemTrustAll]::Accept
        }
    }
    $extra = @{}
    if ($InsecureSkipVerify -and $PSVersionTable.PSVersion.Major -ge 6) { $extra['SkipCertificateCheck'] = $true }

    if (-not $Arch) {
        $Arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64' -or $env:PROCESSOR_ARCHITEW6432 -eq 'ARM64') { 'arm64' } else { 'amd64' }
    }
    $Server = $Server.TrimEnd('/')
    $base = "$Server/downloads"
    $file = "sem-agent-windows-$Arch.exe"
    $tmp = Join-Path ([IO.Path]::GetTempPath()) ("sem-agent-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $tmp | Out-Null
    try {
        Write-Host "Downloading $base/$file"
        Invoke-WebRequest -UseBasicParsing -Uri "$base/$file" -OutFile (Join-Path $tmp $file) @extra
        Invoke-WebRequest -UseBasicParsing -Uri "$base/checksums.txt" -OutFile (Join-Path $tmp 'checksums.txt') @extra

        $expected = $null
        foreach ($line in Get-Content (Join-Path $tmp 'checksums.txt')) {
            $parts = $line.Trim() -split '\s+'
            if ($parts.Count -ge 2 -and $parts[1].TrimStart('*') -eq $file) { $expected = $parts[0].ToLower() }
        }
        if (-not $expected) { throw "No checksum for $file in checksums.txt" }
        $actual = (Get-FileHash -Algorithm SHA256 -Path (Join-Path $tmp $file)).Hash.ToLower()
        if ($actual -ne $expected) { throw "SHA-256 mismatch for ${file}: expected $expected, got $actual" }
        Write-Host "SHA-256 verified: $actual"

        $exe = Join-Path $InstallDir 'sem-agent.exe'
        $svc = Get-Service -Name 'SecureEndpointAgent' -ErrorAction SilentlyContinue
        if ($svc -and $svc.Status -ne 'Stopped') {
            Write-Host 'Stopping existing SecureEndpointAgent service'
            Stop-Service -Name 'SecureEndpointAgent' -Force
            (Get-Service 'SecureEndpointAgent').WaitForStatus('Stopped', [TimeSpan]::FromSeconds(30))
        }
        New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
        Copy-Item -Path (Join-Path $tmp $file) -Destination $exe -Force
        # Binary directory: SYSTEM/Administrators full control, users read/execute only.
        & icacls.exe $InstallDir /inheritance:r /grant:r '*S-1-5-18:(OI)(CI)F' '*S-1-5-32-544:(OI)(CI)F' '*S-1-5-32-545:(OI)(CI)RX' | Out-Null

        $enrollArgs = @('enroll', '--server', $Server, '--token', $Token)
        if ($InsecureSkipVerify) { $enrollArgs += '--insecure-skip-verify' }
        if ($CaFile) { $enrollArgs += @('--ca-file', $CaFile) }
        if ($svc) { $enrollArgs += '--force' }
        & $exe @enrollArgs
        if ($LASTEXITCODE -ne 0) { throw "Enrollment failed (exit code $LASTEXITCODE)" }

        if (-not $svc) {
            & $exe install
            if ($LASTEXITCODE -ne 0) { throw "Service installation failed (exit code $LASTEXITCODE)" }
        }
        & $exe start
        if ($LASTEXITCODE -ne 0) { throw "Service start failed (exit code $LASTEXITCODE)" }
        & $exe status
        Write-Host 'SecureEndpoint agent installed successfully.' -ForegroundColor Green
    }
    finally {
        Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    }
}

# Allow direct invocation: .\install.ps1 -Server ... -Token ...
if ($args.Count -gt 0) { Install-SemAgent @args }
