import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  DeviceType,
  OsPlatform,
  PatchCategory,
  PatchSeverity,
  PatchState,
  ProtectionState,
  UsbDeviceClass,
  UsbEventType,
} from '@prisma/client';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsEnum,
  IsIn,
  IsInt,
  IsISO8601,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
  MinLength,
  ValidateNested,
} from 'class-validator';
import { LenientValidation } from '../common/validation.pipe';

export class NetworkAdapterDto {
  @ApiProperty() @IsString() @MaxLength(200) name: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(64) macAddress?: string;
  @ApiPropertyOptional({ type: [String] }) @IsOptional() @IsArray() @ArrayMaxSize(16) @IsString({ each: true }) @MaxLength(64, { each: true }) ipAddresses?: string[];
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(64) gateway?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) dnsSuffix?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(32) linkSpeed?: string;
}

export class HardwareInfoDto {
  @ApiProperty() @IsString() @MinLength(1) @MaxLength(255) hostname: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) deviceName?: string;
  @ApiProperty() @IsString() @MinLength(1) @MaxLength(128) serialNumber: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(120) manufacturer?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) model?: string;
  @ApiPropertyOptional({ enum: DeviceType }) @IsOptional() @IsEnum(DeviceType) deviceType?: DeviceType;
  @ApiProperty({ enum: OsPlatform }) @IsEnum(OsPlatform) platform: OsPlatform;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(120) osName?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(120) osVersion?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(120) osBuild?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) cpu?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) ramMb?: number;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) storageGb?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(64) ipAddress?: string;
  @ApiPropertyOptional({ type: [String] }) @IsOptional() @IsArray() @ArrayMaxSize(64) @IsString({ each: true }) @MaxLength(64, { each: true }) macAddresses?: string[];
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) loggedInUser?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) domain?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(120) osEdition?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(32) osArch?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(128) biosVersion?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) gpu?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) @Max(100) batteryPercent?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(32) batteryStatus?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(64) gateway?: string;
  @ApiPropertyOptional({ type: [String] }) @IsOptional() @IsArray() @ArrayMaxSize(32) @IsString({ each: true }) @MaxLength(64, { each: true }) dnsServers?: string[];
  @ApiPropertyOptional({ type: [NetworkAdapterDto] }) @IsOptional() @IsArray() @ArrayMaxSize(64) @ValidateNested({ each: true }) @Type(() => NetworkAdapterDto) networkAdapters?: NetworkAdapterDto[];
}

export class ServiceItemDto {
  @ApiProperty() @IsString() @MinLength(1) @MaxLength(255) name: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) displayName?: string;
  @ApiProperty() @IsString() @MaxLength(32) status: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(32) startType?: string;
}

@LenientValidation()
export class EnrollDto {
  @ApiProperty() @IsString() @MinLength(10) @MaxLength(200) enrollmentToken: string;
  @ApiPropertyOptional({ description: 'PEM CSR (RSA 2048+) generated by the agent' }) @IsOptional() @IsString() @MaxLength(16384) csrPem?: string;
  @ApiProperty() @IsString() @MaxLength(64) agentVersion: string;
  @ApiProperty({ type: HardwareInfoDto }) @ValidateNested() @Type(() => HardwareInfoDto) hardware: HardwareInfoDto;
}

@LenientValidation()
export class HeartbeatDto {
  @ApiProperty() @IsString() @MaxLength(64) agentVersion: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) uptimeSec?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) loggedInUser?: string;
}

export class SecurityReportDto {
  @ApiProperty({ enum: ProtectionState }) @IsEnum(ProtectionState) antivirusState: ProtectionState;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) antivirusProduct?: string;
  @ApiPropertyOptional() @IsOptional() @IsISO8601() antivirusSignatureAt?: string;
  @ApiProperty({ enum: ProtectionState }) @IsEnum(ProtectionState) edrState: ProtectionState;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) edrProduct?: string;
  @ApiProperty({ enum: ProtectionState }) @IsEnum(ProtectionState) firewallState: ProtectionState;
  @ApiProperty({ enum: ProtectionState }) @IsEnum(ProtectionState) diskEncryptionState: ProtectionState;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(64) encryptionMethod?: string;
  @ApiPropertyOptional({ enum: ProtectionState }) @IsOptional() @IsEnum(ProtectionState) bitlockerState?: ProtectionState;
  @ApiProperty({ enum: ProtectionState }) @IsEnum(ProtectionState) secureBootState: ProtectionState;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() tpmPresent?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() screenLockEnabled?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) screenLockTimeoutSec?: number;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() passwordOnWake?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() screenSaverEnabled?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() autoUpdateEnabled?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() usbStorageEnabled?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() pendingRebootRequired?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsISO8601() lastBootAt?: string;
  @ApiPropertyOptional({ type: Object }) @IsOptional() @IsObject() raw?: Record<string, unknown>;
}

export class SoftwareItemDto {
  @ApiProperty() @IsString() @MinLength(1) @MaxLength(255) name: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(128) version?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) publisher?: string;
  @ApiPropertyOptional() @IsOptional() @IsISO8601() installDate?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(1024) installLocation?: string;
  @ApiPropertyOptional() @IsOptional() @IsNumber() @Min(0) sizeMb?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(32) source?: string;
}

export class PatchItemDto {
  @ApiProperty() @IsString() @MinLength(1) @MaxLength(200) patchId: string;
  @ApiProperty() @IsString() @MaxLength(500) title: string;
  @ApiPropertyOptional({ enum: PatchCategory }) @IsOptional() @IsEnum(PatchCategory) category?: PatchCategory;
  @ApiPropertyOptional({ enum: PatchSeverity }) @IsOptional() @IsEnum(PatchSeverity) severity?: PatchSeverity;
  @ApiProperty({ enum: PatchState }) @IsEnum(PatchState) state: PatchState;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) product?: string;
  @ApiPropertyOptional({ type: [String] }) @IsOptional() @IsArray() @ArrayMaxSize(200) @IsString({ each: true }) @MaxLength(32, { each: true }) cveIds?: string[];
  @ApiPropertyOptional() @IsOptional() @IsNumber() @Min(0) @Max(10) cvssScore?: number;
  @ApiPropertyOptional() @IsOptional() @IsISO8601() releasedAt?: string;
  @ApiPropertyOptional() @IsOptional() @IsISO8601() installedAt?: string;
}

@LenientValidation()
export class AgentReportDto {
  @ApiProperty() @IsISO8601() collectedAt: string;
  @ApiProperty({ type: HardwareInfoDto }) @ValidateNested() @Type(() => HardwareInfoDto) hardware: HardwareInfoDto;
  @ApiProperty({ type: SecurityReportDto }) @ValidateNested() @Type(() => SecurityReportDto) security: SecurityReportDto;
  @ApiProperty({ type: [SoftwareItemDto] }) @IsArray() @ArrayMaxSize(10000) @ValidateNested({ each: true }) @Type(() => SoftwareItemDto) software: SoftwareItemDto[];
  @ApiProperty({ type: [PatchItemDto] }) @IsArray() @ArrayMaxSize(10000) @ValidateNested({ each: true }) @Type(() => PatchItemDto) patches: PatchItemDto[];
  @ApiPropertyOptional({ type: [ServiceItemDto] }) @IsOptional() @IsArray() @ArrayMaxSize(5000) @ValidateNested({ each: true }) @Type(() => ServiceItemDto) services?: ServiceItemDto[];
}

export class UsbEventItemDto {
  @ApiProperty({ enum: UsbEventType }) @IsEnum(UsbEventType) eventType: UsbEventType;
  @ApiProperty({ enum: UsbDeviceClass }) @IsEnum(UsbDeviceClass) deviceClass: UsbDeviceClass;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(16) vendorId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(16) productId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(128) serialNumber?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) label?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) userName?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(2048) filePath?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) bytes?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(500) policyReason?: string;
  @ApiProperty() @IsISO8601() occurredAt: string;
}

@LenientValidation()
export class UsbEventsDto {
  @ApiProperty({ type: [UsbEventItemDto] }) @IsArray() @ArrayMaxSize(5000) @ValidateNested({ each: true }) @Type(() => UsbEventItemDto) events: UsbEventItemDto[];
}

export class SoftwareEventItemDto {
  @ApiProperty({ enum: ['INSTALLED', 'REMOVED', 'BLOCKED'] }) @IsIn(['INSTALLED', 'REMOVED', 'BLOCKED']) action: 'INSTALLED' | 'REMOVED' | 'BLOCKED';
  @ApiProperty() @IsString() @MinLength(1) @MaxLength(255) name: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(128) version?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) publisher?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(255) userName?: string;
  @ApiProperty() @IsISO8601() occurredAt: string;
}

@LenientValidation()
export class SoftwareEventsDto {
  @ApiProperty({ type: [SoftwareEventItemDto] }) @IsArray() @ArrayMaxSize(5000) @ValidateNested({ each: true }) @Type(() => SoftwareEventItemDto) events: SoftwareEventItemDto[];
}

@LenientValidation()
export class RenewCertificateDto {
  @ApiProperty({ description: 'New PEM CSR (RSA 2048+) generated by the agent' }) @IsString() @MinLength(64) @MaxLength(16384) csrPem: string;
}

@LenientValidation()
export class CommandResultDto {
  @ApiProperty({ enum: ['SUCCEEDED', 'FAILED'] }) @IsIn(['SUCCEEDED', 'FAILED']) status: 'SUCCEEDED' | 'FAILED';
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(65536) output?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(8192) error?: string;
  @ApiPropertyOptional({ type: Object }) @IsOptional() @IsObject() data?: Record<string, unknown>;
}
