#!/usr/bin/env bash
# Regenerates the Kubernetes PrometheusRule from deploy/prometheus/alerts.yml so
# compose and Kubernetes share one set of alert rules.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=deploy/prometheus/alerts.yml
DST=deploy/k8s/components/prometheus-operator/prometheusrule.yaml

{
  cat <<'EOF'
# GENERATED by scripts/sync-prometheusrule.sh from deploy/prometheus/alerts.yml — do not edit.
# The `release` label must match your kube-prometheus-stack ruleSelector.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: secureendpoint
  labels:
    release: kube-prometheus-stack
spec:
EOF
  # Drop leading comment lines, indent the `groups:` document under spec.
  sed -e '/^#/d' -e '/^[[:space:]]*$/d' "$SRC" | sed -e 's/^/  /'
} > "$DST"

echo "wrote $DST"
